In [98]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

In [99]:
data=pd.read_csv('Online retail.csv')

In [100]:
data.head()

  shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
0                             burgers,meatballs,eggs
1                                            chutney
2                                     turkey,avocado
3  mineral water,milk,energy bar,whole wheat rice...
4                                     low fat yogurt

In [101]:
data.columns = ['Items'] + [f'Unused_{i}' for i in range(1, len(data.columns))]
data= data[['Items']]
row=pd.DataFrame(
    [
        {
            'Items':'shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil'
        }
    ]
)
data=pd.concat([data,row],ignore_index=True)
data

                                                  Items
0                                burgers,meatballs,eggs
1                                               chutney
2                                        turkey,avocado
3     mineral water,milk,energy bar,whole wheat rice...
4                                        low fat yogurt
...                                                 ...
7496  burgers,frozen vegetables,eggs,french fries,ma...
7497                                            chicken
7498                                 escalope,green tea
7499    eggs,frozen smoothie,yogurt cake,low fat yogurt
7500  shrimp,almonds,avocado,vegetables mix,green gr...

[7501 rows x 1 columns]

In [102]:
data['Items']=data['Items'].astype(str).apply(lambda x: x.strip('"').split(','))
data

                                                  Items
0                            [burgers, meatballs, eggs]
1                                             [chutney]
2                                     [turkey, avocado]
3     [mineral water, milk, energy bar, whole wheat ...
4                                      [low fat yogurt]
...                                                 ...
7496  [burgers, frozen vegetables, eggs, french frie...
7497                                          [chicken]
7498                              [escalope, green tea]
7499  [eggs, frozen smoothie, yogurt cake, low fat y...
7500  [shrimp, almonds, avocado, vegetables mix, gre...

[7501 rows x 1 columns]

In [103]:
enc=TransactionEncoder()
enc_arr=enc.fit_transform(data['Items'])

In [104]:
enc.columns_

[' asparagus',
 'almonds',
 'antioxydant juice',
 'asparagus',
 'avocado',
 'babies food',
 'bacon',
 'barbecue sauce',
 'black tea',
 'blueberries',
 'body spray',
 'bramble',
 'brownies',
 'bug spray',
 'burger sauce',
 'burgers',
 'butter',
 'cake',
 'candy bars',
 'carrots',
 'cauliflower',
 'cereals',
 'champagne',
 'chicken',
 'chili',
 'chocolate',
 'chocolate bread',
 'chutney',
 'cider',
 'clothes accessories',
 'cookies',
 'cooking oil',
 'corn',
 'cottage cheese',
 'cream',
 'dessert wine',
 'eggplant',
 'eggs',
 'energy bar',
 'energy drink',
 'escalope',
 'extra dark chocolate',
 'flax seed',
 'french fries',
 'french wine',
 'fresh bread',
 'fresh tuna',
 'fromage blanc',
 'frozen smoothie',
 'frozen vegetables',
 'gluten free bar',
 'grated cheese',
 'green beans',
 'green grapes',
 'green tea',
 'ground beef',
 'gums',
 'ham',
 'hand protein bar',
 'herb & pepper',
 'honey',
 'hot dogs',
 'ketchup',
 'light cream',
 'light mayo',
 'low fat yogurt',
 'magazines',
 'mashed potato',
 'mayonnaise',
 'meatballs',
 'melons',
 'milk',
 'mineral water',
 'mint',
 'mint green tea',
 'muffins',
 'mushroom cream sauce',
 'napkins',
 'nonfat milk',
 'oatmeal',
 'oil',
 'olive oil',
 'pancakes',
 'parmesan cheese',
 'pasta',
 'pepper',
 'pet food',
 'pickles',
 'protein bar',
 'red wine',
 'rice',
 'salad',
 'salmon',
 'salt',
 'sandwich',
 'shallot',
 'shampoo',
 'shrimp',
 'soda',
 'soup',
 'spaghetti',
 'sparkling water',
 'spinach',
 'strawberries',
 'strong cheese',
 'tea',
 'tomato juice',
 'tomato sauce',
 'tomatoes',
 'toothpaste',
 'turkey',
 'vegetables mix',
 'water spray',
 'white wine',
 'whole weat flour',
 'whole wheat pasta',
 'whole wheat rice',
 'yams',
 'yogurt cake',
 'zucchini']

In [105]:
data_enc=pd.DataFrame(enc_arr,columns=enc.columns_)
data_enc

,asparagus,almonds,antioxydant juice,asparagus,avocado,babies food,bacon,barbecue sauce,black tea,blueberries,...,turkey,vegetables mix,water spray,white wine,whole weat flour,whole wheat pasta,whole wheat rice,yams,yogurt cake,zucchini
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,True,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7496,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7497,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7498,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7499,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
7500,False,True,True,False,True,False,False,False,False,False,...,False,True,False,False,True,False,False,True,False,False

In [106]:
frequent_itemsets=apriori(data_enc,min_support=0.01,use_colnames=True)
frequent_itemsets

      support                                 itemsets
0    0.020397                                (almonds)
1    0.033329                                (avocado)
2    0.010799                         (barbecue sauce)
3    0.014265                              (black tea)
4    0.011465                             (body spray)
..        ...                                      ...
252  0.011065       (milk, mineral water, ground beef)
253  0.017064  (mineral water, ground beef, spaghetti)
254  0.015731         (milk, mineral water, spaghetti)
255  0.010265    (olive oil, mineral water, spaghetti)
256  0.011465     (pancakes, mineral water, spaghetti)

[257 rows x 2 columns]

In [112]:
assoc_rules=association_rules(frequent_itemsets,min_threshold=0.3)
assoc_rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(avocado),(mineral water),0.033329,0.238368,0.011598,0.348000,1.459926,1.0,0.003654,1.168147,0.325896,0.044593,0.143943,0.198329
1,(burgers),(eggs),0.087188,0.179709,0.028796,0.330275,1.837830,1.0,0.013128,1.224818,0.499424,0.120941,0.183552,0.245256
2,(cake),(mineral water),0.081056,0.238368,0.027463,0.338816,1.421397,1.0,0.008142,1.151921,0.322617,0.094064,0.131885,0.227014
3,(cereals),(mineral water),0.025730,0.238368,0.010265,0.398964,1.673729,1.0,0.004132,1.267198,0.413162,0.040441,0.210857,0.221014
4,(chicken),(mineral water),0.059992,0.238368,0.022797,0.380000,1.594172,1.0,0.008497,1.228438,0.396502,0.082729,0.185958,0.237819
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,"(milk, spaghetti)",(mineral water),0.035462,0.238368,0.015731,0.443609,1.861024,1.0,0.007278,1.368879,0.479672,0.060950,0.269475,0.254802
59,"(olive oil, mineral water)",(spaghetti),0.027596,0.174110,0.010265,0.371981,2.136468,1.0,0.005460,1.315071,0.547034,0.053621,0.239585,0.215470
60,"(olive oil, spaghetti)",(mineral water),0.022930,0.238368,0.010265,0.447674,1.878079,1.0,0.004799,1.378954,0.478514,0.040892,0.274813,0.245370
61,"(pancakes, mineral water)",(spaghetti),0.033729,0.174110,0.011465,0.339921,1.952333,1.0,0.005593,1.251198,0.504819,0.058384,0.200766,0.202885
62,"(pancakes, spaghetti)",(mineral water),0.025197,0.238368,0.011465,0.455026,1.908923,1.0,0.005459,1.397557,0.488452,0.045479,0.284466,0.251562

In [120]:
rules=assoc_rules[assoc_rules['lift']>1]

In [121]:
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(avocado),(mineral water),0.033329,0.238368,0.011598,0.348000,1.459926,1.0,0.003654,1.168147,0.325896,0.044593,0.143943,0.198329
1,(burgers),(eggs),0.087188,0.179709,0.028796,0.330275,1.837830,1.0,0.013128,1.224818,0.499424,0.120941,0.183552,0.245256
2,(cake),(mineral water),0.081056,0.238368,0.027463,0.338816,1.421397,1.0,0.008142,1.151921,0.322617,0.094064,0.131885,0.227014
3,(cereals),(mineral water),0.025730,0.238368,0.010265,0.398964,1.673729,1.0,0.004132,1.267198,0.413162,0.040441,0.210857,0.221014
4,(chicken),(mineral water),0.059992,0.238368,0.022797,0.380000,1.594172,1.0,0.008497,1.228438,0.396502,0.082729,0.185958,0.237819
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,"(milk, spaghetti)",(mineral water),0.035462,0.238368,0.015731,0.443609,1.861024,1.0,0.007278,1.368879,0.479672,0.060950,0.269475,0.254802
59,"(olive oil, mineral water)",(spaghetti),0.027596,0.174110,0.010265,0.371981,2.136468,1.0,0.005460,1.315071,0.547034,0.053621,0.239585,0.215470
60,"(olive oil, spaghetti)",(mineral water),0.022930,0.238368,0.010265,0.447674,1.878079,1.0,0.004799,1.378954,0.478514,0.040892,0.274813,0.245370
61,"(pancakes, mineral water)",(spaghetti),0.033729,0.174110,0.011465,0.339921,1.952333,1.0,0.005593,1.251198,0.504819,0.058384,0.200766,0.202885
62,"(pancakes, spaghetti)",(mineral water),0.025197,0.238368,0.011465,0.455026,1.908923,1.0,0.005459,1.397557,0.488452,0.045479,0.284466,0.251562

In [122]:
rules.sort_values(by='confidence', ascending=False).head(10)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
45,"(ground beef, eggs)",(mineral water),0.019997,0.238368,0.010132,0.506667,2.125563,1.0,0.005365,1.543848,0.540342,0.040816,0.352268,0.274586
54,"(milk, ground beef)",(mineral water),0.021997,0.238368,0.011065,0.503030,2.110308,1.0,0.005822,1.532552,0.537969,0.044385,0.347493,0.274725
39,"(chocolate, ground beef)",(mineral water),0.023064,0.238368,0.010932,0.473988,1.988472,1.0,0.005434,1.447937,0.508837,0.043640,0.309362,0.259925
50,"(milk, frozen vegetables)",(mineral water),0.023597,0.238368,0.011065,0.468927,1.967236,1.0,0.005440,1.434136,0.503555,0.044102,0.302716,0.257674
28,(soup),(mineral water),0.050527,0.238368,0.023064,0.456464,1.914955,1.0,0.011020,1.401255,0.503221,0.086760,0.286354,0.276610
62,"(pancakes, spaghetti)",(mineral water),0.025197,0.238368,0.011465,0.455026,1.908923,1.0,0.005459,1.397557,0.488452,0.045479,0.284466,0.251562
60,"(olive oil, spaghetti)",(mineral water),0.022930,0.238368,0.010265,0.447674,1.878079,1.0,0.004799,1.378954,0.478514,0.040892,0.274813,0.245370
58,"(milk, spaghetti)",(mineral water),0.035462,0.238368,0.015731,0.443609,1.861024,1.0,0.007278,1.368879,0.479672,0.060950,0.269475,0.254802
40,"(chocolate, milk)",(mineral water),0.032129,0.238368,0.013998,0.435685,1.827780,1.0,0.006340,1.349656,0.467922,0.054574,0.259071,0.247205
56,"(ground beef, spaghetti)",(mineral water),0.039195,0.238368,0.017064,0.435374,1.826477,1.0,0.007722,1.348914,0.470957,0.065507,0.258663,0.253481

### Interpretation
The above provided rules are top 10 rules give out a strong confidence within the given dataset with strong correlation.
Around 40 to 50 percent of transactions that brought the antecendents are likely to buy the consequents(mineral water).

The association rule analysis reveals clear patterns in customer purchasing behavior, indicating that many shoppers tend to buy items that complement each other in meal preparation. For instance, products like herb & pepper are strongly associated with ground beef, and ground beef frequently co-occurs with spaghetti, suggesting that customers often plan meals such as pasta dishes while shopping. Additionally, staple items like mineral water and spaghetti appear as common additions to a wide range of baskets, highlighting their role as everyday essentials.

### 1. What is Lift and Why Is It Important in Association Rules?

**Lift** measures how much more likely two items are to be purchased together compared to being bought independently. It is calculated as the ratio of the observed co-occurrence of items to the expected co-occurrence if they were independent. A lift value greater than 1 indicates a positive association, while less than 1 implies a negative association. Lift is important because it helps identify truly meaningful rules by filtering out coincidental co-purchases. Unlike confidence, lift adjusts for item popularity, making it a better metric for uncovering strong and non-trivial relationships between products in market basket analysis.


### 2. What is Support and Confidence? How Are They Calculated?

**Support** measures how frequently an itemset appears in the dataset. It is calculated as the proportion of transactions that contain the itemset:
Support(A,B) = (Transactions containing A and B) / (Total transactions)
**Confidence** measures the likelihood that a ruleâ€™s consequent appears in transactions that contain the antecedent:
Confidence(A â‡’ B) = Support(A and B) / Support(A)
Support helps identify common itemsets, while confidence reflects the strength of occurance. Both are essential in evaluating rule relevance association rule mining, guiding which rules to keep.


### 3. What Are Some Limitations or Challenges of Association Rule Mining?

Association rule mining has several limitations such as, 
It often generates a large number of rules, many of which may be trivial or uninteresting, leading to analysis overload. 

Setting appropriate thresholds for support and confidence is challengingâ€”too low may yield noise, while too high may miss useful patterns. 

It also struggles with sparse or high-dimensional data, where meaningful patterns are rare.  

Popular items may dominate results unless lift or other measures are used, making it harder to detect less obvious but valuable associations.